export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just For You",
        description:
            "Get interview question and model answer based on your role, experience, and specific focus area - no generic practice here"
    },
    {
        id: "02",
        title: "Learn at your own Pace",
        description:
            "Expand answers only when youßre ready. Dive deeper into any concept instantly with Al-powered detailed explanation"
    },
    {
        id: "03",
        title: "Capture Youre Insight",
        description:
            "Add personal notes to any question and pin important ones to the top-making your learning more organized and impactful"
    },
    {
        id: "04",
        title: 'Understand the "WHY" Behind Answers',
        description:
            "Beyond just answers unlock detailed concept explanations generated by Al, helping you truly master each topic"
    },
    {
        id: "05",
        title: "Save Organize, and Revisit",
        description:
            "Easily save your interview sets, organize thes neatly in your dashboard, and pick up your preparation right where you left off"
    }

];